# Generated by Django 4.2.7 on 2026-06-22 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_owner_alter_project_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('writer_vision', '视觉识别专家（图片型PDF）'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='GeneratedRequirementDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='文档标题')),
                ('markdown_content', models.TextField(verbose_name='Markdown 内容')),
                ('source_type', models.CharField(choices=[('text', '粘贴文字'), ('file', '上传文件'), ('template', '空白模板')], max_length=20, verbose_name='来源类型')),
                ('source_detail', models.TextField(blank=True, help_text='文件名列表或粘贴文字摘要', verbose_name='来源详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_req_docs', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '生成的需求文档',
                'verbose_name_plural': '生成的需求文档',
                'db_table': 'generated_requirement_docs',
                'ordering': ['-created_at'],
            },
        ),
    ]
