# Generated by Django 4.2.7 on 2026-06-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
        ('requirement_analysis', '0002_alter_aimodelconfig_role_generatedrequirementdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='versions.version', verbose_name='关联版本'),
        ),
    ]
