# Generated by Django 4.2.7 on 2026-06-23 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_modules', '__first__'),
        ('requirement_analysis', '0003_testcasegenerationtask_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='feature_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='feature_modules.featuremodule', verbose_name='关联功能模块'),
        ),
    ]
