# Generated by Django 4.2.7 on 2026-06-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0004_testcasegenerationtask_feature_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='generation_mode',
            field=models.CharField(choices=[('quick', '快速模式'), ('standard', '标准模式'), ('comprehensive', '全面模式')], default='standard', max_length=20, verbose_name='生成模式'),
        ),
    ]
