# Generated by Django 4.2.7 on 2026-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0005_add_testcase_generation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasegenerationtask',
            name='generation_mode',
            field=models.CharField(choices=[('smart', '智能模式'), ('quick', '快速模式'), ('standard', '标准模式'), ('comprehensive', '全面模式')], default='smart', max_length=20, verbose_name='生成模式'),
        ),
    ]
