# Generated by Django 4.2.7 on 2026-06-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature_modules', '0002_testpoint'),
        ('requirement_analysis', '0006_alter_testcasegenerationtask_generation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='feature_modules.testpoint', verbose_name='关联测试点'),
        ),
    ]
