# Generated by Django 4.2.7 on 2026-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0007_testcasegenerationtask_test_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='human_feedback',
            field=models.TextField(blank=True, verbose_name='人工确认回复'),
        ),
    ]
