# Generated by Django 4.2.7 on 2026-06-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0009_testcasegenerationtask_kb_audit_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='评审次数'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='review_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后评审时间'),
        ),
    ]
