# Generated by Django 4.2.7 on 2026-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0010_add_review_count_and_review_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='结果标题')),
                ('requirement_text', models.TextField(blank=True, verbose_name='拆解的需求文本')),
                ('result_content', models.TextField(verbose_name='拆解结果（Markdown）')),
                ('content_preview', models.TextField(blank=True, verbose_name='内容预览')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '需求拆解结果',
                'verbose_name_plural': '需求拆解结果',
                'db_table': 'requirement_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('writer_vision', '视觉分析专家（截图/图片/PDF）'), ('reviewer', '测试评审专家'), ('analyzer', '需求拆解专家'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(choices=[('writer', '用例编写提示词'), ('reviewer', '用例评审提示词'), ('analyzer', '需求分析提示词')], max_length=20, verbose_name='提示词类型'),
        ),
    ]
