# Generated by Django 4.2.7 on 2026-07-13 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0011_requirementanalysisresult_alter_aimodelconfig_role_and_more'),
        ('projects', '0007_remove_project_idx_project_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementanalysisresult',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='requirementanalysisresult',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_analysis_results', to='projects.project', verbose_name='关联项目'),
        ),
    ]
