# Generated by Django 4.2.7 on 2026-06-16 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='知识条目标题')),
                ('category', models.CharField(choices=[('background', '业务背景'), ('terminology', '关键术语'), ('test_focus', '测试重点'), ('constraints', '约束条件'), ('notes', '注意事项')], default='background', max_length=20, verbose_name='分类')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目知识库',
                'verbose_name_plural': '项目知识库',
                'db_table': 'project_knowledge',
                'ordering': ['category', 'sort_order', '-created_at'],
            },
        ),
    ]
