# Generated by Django 4.2.7 on 2026-06-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='knowledge_base_path',
            field=models.CharField(blank=True, default='', help_text='服务器上知识库 markdown 文件的绝对路径，留空则不启用文件型知识库', max_length=500, verbose_name='知识库文件目录'),
        ),
    ]
