# Generated by Django 4.2.7 on 2026-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['creator'], name='idx_testplan_creator'),
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=models.Index(fields=['is_active'], name='idx_testplan_is_active'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['project'], name='idx_testrun_project'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['status'], name='idx_testrun_status'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['assignee'], name='idx_testrun_assignee'),
        ),
        migrations.AddIndex(
            model_name='testruncase',
            index=models.Index(fields=['testcase'], name='idx_testruncase_testcase'),
        ),
        migrations.AddIndex(
            model_name='testruncase',
            index=models.Index(fields=['status'], name='idx_testruncase_status'),
        ),
    ]
