# Generated by Django 4.2.7 on 2026-07-13 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_remove_project_idx_project_owner_and_more'),
        ('testsuites', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0008_alter_testcase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsuites', to='projects.project'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='testcases',
            field=models.ManyToManyField(through='testsuites.TestSuiteCase', to='testcases.testcase', verbose_name='测试用例'),
        ),
        migrations.AlterUniqueTogether(
            name='testsuitecase',
            unique_together={('testsuite', 'testcase')},
        ),
    ]
