# Generated by Django 4.2.7 on 2026-06-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_modules', '__first__'),
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='feature_modules',
            field=models.ManyToManyField(blank=True, related_name='testcases', to='feature_modules.featuremodule', verbose_name='关联功能模块'),
        ),
    ]
