# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcase_test_points'),
        ('feature_modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_points',
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='feature_modules.testpoint', verbose_name='关联测试点'),
        ),
    ]
