# Generated by Django 4.2.7 on 2026-06-29 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0004_remove_testcase_test_points_testcase_test_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '失败')], max_length=10, verbose_name='执行结果')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testcases.testcase')),
            ],
            options={
                'verbose_name': '测试用例执行记录',
                'verbose_name_plural': '测试用例执行记录',
                'db_table': 'testcase_executions',
                'ordering': ['-executed_at'],
            },
        ),
    ]
