# Generated by Django 4.2.7 - recreated to fix missing migration file

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_project',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_status',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_priority',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_author',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_test_type',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_created_at',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_project_status',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_project_priority',
        ),
        migrations.RemoveIndex(
            model_name='testcaseexecution',
            name='idx_tc_exec_testcase',
        ),
        migrations.RemoveIndex(
            model_name='testcaseexecution',
            name='idx_tc_exec_executed_by',
        ),
        migrations.RemoveIndex(
            model_name='testcaseexecution',
            name='idx_tc_exec_executed_at',
        ),
    ]
