# Generated by Django 4.2.7 on 2026-07-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_remove_testcase_idx_testcase_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['created_at'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
    ]
