# Generated by Django 4.2.7 on 2026-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_initial'),
        ('testcases', '0008_alter_testcase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='testcases', to='versions.version', verbose_name='关联版本'),
        ),
    ]
