# Generated by Django 4.2.7 on 2026-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_testcase_versions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['sort_order', 'created_at', 'id'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AddField(
            model_name='testcase',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='排序序号'),
        ),
    ]
