# Generated by Django 4.2.7 on 2026-06-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feature_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='测试点名称')),
                ('description', models.TextField(blank=True, verbose_name='测试点描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('feature_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_points', to='feature_modules.featuremodule', verbose_name='关联功能模块')),
            ],
            options={
                'verbose_name': '测试点',
                'verbose_name_plural': '测试点',
                'db_table': 'test_points',
                'ordering': ['feature_module', 'name'],
                'unique_together': {('feature_module', 'name')},
            },
        ),
    ]
