# Generated by Django 4.2.7 on 2026-07-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_initial'),
        ('feature_modules', '0002_testpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuremodule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feature_modules.featuremodule', verbose_name='父模块'),
        ),
        migrations.AddField(
            model_name='featuremodule',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='feature_modules', to='versions.version', verbose_name='关联版本'),
        ),
    ]
