# Generated by Django 4.2.7 on 2026-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdevice',
            name='adb_host',
            field=models.CharField(blank=True, default='', help_text='手机USB所在电脑的 IP:PORT（如 192.168.8.71:5037），后端通过该电脑的ADB服务控制此设备', max_length=50, null=True, verbose_name='ADB主机'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='标签'),
        ),
    ]
